
[scrolling]
history = 65535

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[env]
# WINIT_X11_SCALE_FACTOR = "1.25"

[window]
decorations = "none"
padding = { x = 0, y = 0 }
opacity = 0.9
# blur = true
startup_mode = "Maximized"

[font]
size = 11
offset = { x = 0, y = 0 }
normal      = { family = "FiraCode Nerd Font", style = "Medium" }
# bold        = { family = "FiraCode Nerd Font Mono", style = "Bold" }
# italic      = { family = "FiraCode Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

[colors.cursor]
cursor = "#00FF00"

[cursor]
blink_interval = 200
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]

[general]
import = ["/home/byomess/.config/alacritty/themes/themes/iterm.toml"]

[terminal]
